### ISSUE TITLE
Can't Execute this version

### ISSUE THREAD

**Issue by pranjal123saxena** [antony-jr/instagram-py#10]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

You are surely a genius man! But I can't Execute this it's showing an error.

Error: Error executing 'instagram-py-wrapper' : No Such file or Driectory

**Comment by pranjal123saxena** [comment]
![img_20180401_111224791](https://user-images.githubusercontent.com/37745131/38170250-a1808596-359d-11e8-92b3-5efd52046b14.jpg)
Tried renaming the file in /use/bin/ to instagram-py-wrapper

**Comment by pranjal123saxena** [comment]
![img_20180401_111557492](https://user-images.githubusercontent.com/37745131/38170266-284b6758-359e-11e8-9efd-596884a7741f.jpg)
THE ORIGINAL ISSUE..

**Comment by antony-jr** [comment]
@pranjal123saxena just wait a bit , I will test this on kali linux

**Comment by antony-jr** [comment]
@pranjal123saxena  Everything should work fine now, 
Use this [application](https://github.com/antony-jr/AppImageUpdater) to update instagram-py , This helps you download less data on updates!  You can also just download the new version!

**Comment by pranjal123saxena** [comment]
Nothing's Working Antony :/ @antony-jr

**Comment by antony-jr** [comment]
@pranjal123saxena please wait...

**Comment by antony-jr** [comment]
@pranjal123saxena Please update again , This version is confirmed to work!

**Comment by pranjal123saxena** [comment]
How to update it? it keeps on showing the same error "No file or Directory" Can you write me the command to update it? I have downloaded and extracted the file to desktop.

**Comment by pranjal123saxena** [comment]
oh by update i meant that Appimages application which doesn't seem to work not instagram-py.

**Comment by antony-jr** [comment]
@pranjal123saxena just repeat the installation process given in readme of the project page... You can also download the AppImage directly and use it.
