### ISSUE TITLE
Cant execute (again)

### ISSUE THREAD

**Issue by noammiz007** [antony-jr/instagram-py#11]
@antony-jr 

**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:*when i execute the instagram-py portable tool so i get an error, something about site: https://user-images.githubusercontent.com/31467235/38173599-a553305c-35c9-11e8-9480-4be2315102b1.png*

**Ways to Reproduce the issue (optional):**

**Comment by antony-jr** [comment]
Just got this , looking into it!

**Comment by noammiz007** [comment]
@antony-jr i just updated and another problem:
![default](https://user-images.githubusercontent.com/31467235/38174213-a1368c54-35d2-11e8-8901-acf037074cbf.png)

**Comment by noammiz007** [comment]
The problem has been fixed
