### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by Mehran** [antony-jr/instagram-py#12]
i'm not sure here right but can create it to make for twitter also ?

**Comment by antony-jr** [comment]
@Mehran  No problem not here but in a new repo! Lets call it twitter-py

**Comment by Mehran** [comment]
wow cool waiting for twitter-py

**Comment by antony-jr** [comment]
@Mehran See this project , The author has a similar tool for instagram too... https://github.com/thelinuxchoice/tweetshell , I guess there is no need for twitter-py

**Comment by Mehran** [comment]
its not work good i looking something pro like instapy

**Comment by antony-jr** [comment]
No problem.
