### ISSUE TITLE
Completely Confused

### ISSUE THREAD

**Issue by pranjal123saxena** [antony-jr/instagram-py#14]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

Step-1 $ sudo wget -O /usr/bin/instagram-py https://git.io/vxKaq; sudo chmod +x /usr/bin/instagram-py
Step-2 ????????

Now what? What do i have to do next? On the release page there is no other step than this and as you have said there's no need to install any tor server or any python or anything. It should be able to work right away but i am not getting what to do next.. how to use that appimages application? Tried downloading..but commands didn't work. Tried Drag & Drop, still didn't work. Please help

Ealier in Instagram-py to execute, we used to write

$ Instagram-py -c -vv -u <username> -pl /path/to/wordlist.txt

What do we have to write in this update to make it work??? Totally Confused.
Please help.

**Comment by antony-jr** [comment]
@pranjal123saxena just do **Step-1** to update... and  just use it.
This is what you have to do to make it work.

``` 
$ sudo wget -O /usr/bin/instagram-py https://git.io/vxKaq;sudo chmod +x /usr/bin/instagram-py
$ instagram-py # just use it!
```

**Comment by antony-jr** [comment]
@pranjal123saxena Here is a video on the usage of **Instagram-Py Portable** , https://www.youtube.com/watch?v=nNfSyI_Q9SM

**Comment by pranjal123saxena** [comment]
![img_20180402_073545767](https://user-images.githubusercontent.com/37745131/38180254-cb835ade-3648-11e8-853f-3f68e97b6d91.jpg)

This error

**Comment by pranjal123saxena** [comment]
That video is not in Kali linux..right? I will try that too..

**Comment by antony-jr** [comment]
@pranjal123saxena To fix the error that you mentioned in the picture , Please change your clock to correct time , I know its silly but Tor server heavily depends on the systems time...

**Comment by pranjal123saxena** [comment]
The clock is showing the right time @antony-jr

**Comment by pranjal123saxena** [comment]
I am from India..does that make any difference? Like time zones or something?

**Comment by antony-jr** [comment]
**and Make sure you have no tor services runing**.

**Comment by antony-jr** [comment]
@pranjal123saxena does it work now ?

**Comment by pranjal123saxena** [comment]
No..no tor services are running..but after setting the clock it asks to restart the system and when I do that in live boot it gets stuck here..
![img_20180402_080111360](https://user-images.githubusercontent.com/37745131/38180678-16df698e-364c-11e8-9f36-c63ce8be0539.jpg)

**Comment by antony-jr** [comment]
@pranjal123saxena don't restart in a live boot , just change the time and try again.

**Comment by pranjal123saxena** [comment]
Can't find actual settings for clock..am I doing it correctly?
![img_20180402_080917131](https://user-images.githubusercontent.com/37745131/38180897-52bfda0a-364d-11e8-817e-2e6de7b0d864.jpg)

**Comment by antony-jr** [comment]
@pranjal123saxena Is everything working ?

**Comment by pranjal123saxena** [comment]
I have restarted in live boot..I will update after installing Instagram-py again.. I hope this time it will start working..thank you @antony-jr  :)

**Comment by antony-jr** [comment]
Next time you download Instagram-Py , Copy it to a thumb drive , This way you could just start using instagram-py when you have a live boot!

**Comment by pranjal123saxena** [comment]
You are genius dude! It's working now!!!
Thank you! Thank you so much @antony-jr  :) :)

**Comment by antony-jr** [comment]
That sounds good to me.

**Comment by pranjal123saxena** [comment]
Again..I don't know why..
![img_20180402_100446549](https://user-images.githubusercontent.com/37745131/38183337-51070e9e-365d-11e8-8a36-3bd6a9e12caf.jpg)

**Comment by antony-jr** [comment]
If you face this error then execute this command ``` $ kill $(pidof tor) ```

**Comment by antony-jr** [comment]
dont use multiple instances of instagram-py , Instead use instagram-py scripting.

**Comment by pranjal123saxena** [comment]
Thanks @antony-jr  it started working again..can you suggest me some good wordlists?? Or can we speed this up? It's taking so much time and with a wordlist containing 10 million passwords, it will take months to check all of them..if I somehow manage to run it for that many months.. :P 
Other than this Instagram-py is running smoothly and it's the best tool I have found on the internet! Thank you so much for this! Make one for Facebook too! Please! :D

**Comment by antony-jr** [comment]
@pranjal123saxena If I have time I would make this for facebook too... Use tools like [cupps](https://github.com/Mebus/cupp) to make your custom wordlist just for your victim , Please see that brute force is only efficient if you use the victim's personel information to generate the wordlist ( Use social engineering to get the info out them like how **eliot does in Mr.Robot** [ He always uses brute force attack to social media's of his victims ] ).
Thank you for trying out instagram-py.
