### ISSUE TITLE
Tor configuration invalid or server down errno 111

### ISSUE THREAD

**Issue by ahmetu66** [antony-jr/instagram-py#16]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

Hi how do I fix this error with the server? 

Thank you!

**Ways to Reproduce the issue (optional):**

**Comment by noammiz007** [comment]
Screenshot

**Comment by noammiz007** [comment]
Are you using the appimage version?

**Comment by ahmetu66** [comment]
No I am using the pip version

**Comment by noammiz007** [comment]
I suggest you to get the appimage version. Its all in one pack and you dont need tor

**Comment by ahmetu66** [comment]
do you know how to uninstall everything at once so there are no conflicts? I am doing this from a raspberry pi

**Comment by noammiz007** [comment]
Well. Just delete the folder

**Comment by noammiz007** [comment]
And install the appimage

**Comment by noammiz007** [comment]
There wont be conflicts i did it too

**Comment by ahmetu66** [comment]
going to try that and comment back on you, thanks!

**Comment by ahmetu66** [comment]
should I uninstall tor? I can't find the instagram-py folder

**Comment by noammiz007** [comment]
After you download you need to give it permissions with
chmod +x

**Comment by noammiz007** [comment]
Ok

**Comment by ahmetu66** [comment]
bash: ./Instagram-Py-continuous-x86_64.AppImage: cannot execute binary file: Exec format error

I am getting this error with the download, what can I do?

**Comment by antony-jr** [comment]
@ahmetu66 Thats because its clear that AppImage's are currently for 64 Bit and not **arm** which raspberry pi uses , you have to use pip to get instagram-py!

**Comment by antony-jr** [comment]
@ahmetu66 did you install tor server and other stuff mentioned in the installation section. And you need to configure tor and instagram-py , Its given in the README , go through it.

**Comment by ahmetu66** [comment]
hi antony! 

i've gone through the whole README, but still getting the invalid server error. 

you wrote: make sure your tor configuration matched ~/instapy-config.json 

how do i check this? When I enter with sudo nano instapy-config.json the file is empy, maybe this is causing the problem?

thanks for the help!

**Comment by antony-jr** [comment]
@ahmetu66 Install tor server , execute this command in instagram-py ``` $ instagram-py -cc ``` to create the configuration. , Start the tor server , now execute the attack.

The configuration has to be done just once.

**Comment by antony-jr** [comment]
and for every change you make in the torrc , Restart your tor server.

**Comment by ahmetu66** [comment]
I had done all those, tried again and also restart tor server but still not working bro.. still giving the error invalid server

**Comment by antony-jr** [comment]
@ahmetu66 Okay I will try it in my raspberry pi , Please make sure that you are connected to the internet and check the configuration file located at ~/instapy-config.json

**Comment by noammiz007** [comment]
@ahmetu66 
Try this:
Step 1: uninstall tor with 
> apt-get purge tor
Step 2: reinstall tor with
> apt-get install tor
Step 3: remove the "#" in the tor config in the portcontrol
Step 4: fire up terminal and type 
> service tor start
Step 5: type "instagram-py -cc"
And inthe ip type 127.0.0.1
In port type 9050
In portcontrol type 9051
And in password dont type anything and then press enter
And then try the tool again

**Comment by antony-jr** [comment]
@ahmetu66 Also check if you have openned the control port in tor server

**Comment by ahmetu66** [comment]
guys thanks, that's working, but getting another error now : 

Tor configuration invalid or server down :: Authentication failed: unable to read '/var/run/tor/control.authcookie' ([Errno 13] Permission denied: '/var/run/tor/control.authcookie')

**Comment by noammiz007** [comment]
@ahmetu66 type "instagram-py -cc" and do tge steps i said

**Comment by noammiz007** [comment]
@ahmetu66 start from step 5

**Comment by ahmetu66** [comment]
could it be this? 

timedatectl
      Local time: Mon 2018-04-02 18:24:14 UTC
  Universal time: Mon 2018-04-02 18:24:14 UTC
        RTC time: n/a
       Time zone: Etc/UTC (UTC, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no

my time here is 20:24

how should I set this up right?

**Comment by antony-jr** [comment]
@ahmetu66 use it with **sudo**.

**Comment by antony-jr** [comment]
@ahmetu66 When you have permission error , always use **sudo** , your issue is similar to https://github.com/antony-jr/instagram-py/issues/4

**Comment by ahmetu66** [comment]
it is working now! thanks guys!!

**Comment by antony-jr** [comment]
That sounds good!
