### ISSUE TITLE
Continue script where it stopped

### ISSUE THREAD

**Issue by ahmetu66** [antony-jr/instagram-py#17]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

Hi, is there a way for the script to recognize where he left with the loaded text document, when say the attack stopped and you don't want to start all over again. Maybe a suggestion if it is possible?

**Ways to Reproduce the issue (optional):**

**Comment by antony-jr** [comment]
@ahmetu66 There is a feature like this , **Just add '-c' argument to the command to resume the attack if the username was brute forced previously with the same password list** 

**Example:**

```
 $ instagram-py -u alanturing0 -pl /usr/share/wordlists/rockyou.txt -c # Thats It
```

**Comment by antony-jr** [comment]
Take a look at this video -> https://www.youtube.com/watch?v=nNfSyI_Q9SM

**Comment by antony-jr** [comment]
Or are you refering to some other feature ?

**Comment by antony-jr** [comment]
**Caution**: If you start the attack again without the **-c** argument the save data will be destroyed. I will add a confirmation to the user in the near future maybe.

**Comment by ahmetu66** [comment]
Yes I think I was looking for that. In the night the script had stopped working, Maybe because of my pi, so in the morning I had to start all over with my 10 million pass text document. 

Thanks for the help, I Will implement the -c argument if it stops again!
