### ISSUE TITLE
Get the new instagram-Py!

### ISSUE THREAD

**Issue by antony-jr** [antony-jr/instagram-py#2]
**CC** : @perezpaya  @glerinsonum @ROOTH4CK3R @Drudude

> 💼 Instagram-Py is a professional tool to 🎱 brute force instagram 📸 accounts with less resource 🎁 as possible , Written in Python 🐍 and made with ❤️ -- Antony Jr.

You are invited to this repo because I think this project may help you. Please see that there are many fake clones of **Instagram-Py** but this is the original upstream pypi package repo. Verify it by using git log on other fake clones and the official pypi package [here](https://pypi.python.org/pypi/instagram-py) ( **The Author Should be me** 😄 ) , This is the pypi package that is used from long ago , So I think you get who is the real author. Thank You For Your Time! Please Avoid this if you find it useless , Feel free to raise issues to get them fixed asap.

[Click here for more information.](https://github.com/antony-jr/instagram-py/)
**VIDEO TUTORIAL** : https://www.youtube.com/watch?v=KZEcFn3Z5L0

**Comment by sleazerrrr** [comment]
Hey man I’m having trouble with my path for my wordlist every time I choose it , it says password list not found , it’s currently on my desktop , but in a folder. Currently in root but I switched to my origina login and still got the same thing I’m not sure what I’m doing wrong

**Comment by antony-jr** [comment]
@sleazerrrr could you cd to desktop and try again ?

**Comment by sleazerrrr** [comment]
I tried it last night before it went to sleep and it worked fine , woke up this morning and the terminal was closed atuamtically so I thought maybe it just finished , but I checked if any password was logged and nothing and now I’m trying the same thing again and now it’s sayin no password list found . This is what It looks like typed
root@hoest:-/Desktop# sudo instagram-py -u (username) -pl ~/Desktop/Wordlists/easypasswordlist.txt

**Comment by antony-jr** [comment]
@sleazerrrr are you logged in as a normal user ?

**Comment by antony-jr** [comment]
@sleazerrrr You can also check the cracked users with this command , ``` $ instagram-py -i (username) ```

**Comment by sleazerrrr** [comment]
I am now currently and tried it again and same thing , I feel like it’s something so simple that I’m missing

**Comment by sleazerrrr** [comment]
Is there any way I could send you a picture of what it looks like

**Comment by antony-jr** [comment]
@sleazerrrr please post the output of ``` $ ls ```

**Comment by antony-jr** [comment]
@sleazerrrr you could send a pic with https://imgur.com

**Comment by sleazerrrr** [comment]
https://imgur.com/a/mrDfd

**Comment by antony-jr** [comment]
do you have your **Wordlists** directory on desktop ?

**Comment by sleazerrrr** [comment]
https://imgur.com/a/Zr8ad 
https://imgur.com/a/UJb6S 
Yesss sirrr

**Comment by antony-jr** [comment]
are you logged in as a normal user ?

**Comment by sleazerrrr** [comment]
Yeah you can see it in the photo I’m signed in as Castiel , gonna restart my computer and see what happens

**Comment by antony-jr** [comment]
@sleazerrrr Try this command , It should work , ``` $ instagram-py  -u (username) -pl Wordlists/passwordlist.txt ```

**Comment by antony-jr** [comment]
If you have any doubts , Get in the live chat here , https://discord.gg/Pwe3Uq
