### ISSUE TITLE
cant update

### ISSUE THREAD

**Issue by noammiz007** [antony-jr/instagram-py#22]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:*when i am trying to update i get this 
![default](https://user-images.githubusercontent.com/31467235/38428940-b40b61be-39c5-11e8-8d44-32b827b6e05a.png)
*

**Ways to Reproduce the issue (optional):**

**Comment by noammiz007** [comment]
problem: 
whene i start the AppImage updater i get this:

![default](https://user-images.githubusercontent.com/31467235/38429277-9fb1ce96-39c6-11e8-92fc-302771b35538.png)

**Comment by noammiz007** [comment]
nvm again clock problem.. fixed

**Comment by antony-jr** [comment]
@noammiz007 I need to disclose something , **Continuous Integration** is truly a continuous process , Literally , Whenever I make a change (i.e Even if I edit the readme ) a new build is triggered in a remote server , This server builds everything , packs and uploads it to the github releases using my github token. Looks interesting right , **The build logs always gets here ->** https://travis-ci.org/antony-jr/instagram-py

So only update if the build changes major stuff and not a simple README.rst , I will later ,  Make the server trigger new builds when I tag a new version.

**During this time , When you update , it will fail.** (Just wait for 20 Minutes whenever a new commit is commited).

**Comment by noammiz007** [comment]
ok
