### ISSUE TITLE
cant execute

### ISSUE THREAD

**Issue by ficopang** [antony-jr/instagram-py#3]
im using windows when i try execute "instagram-py -c -vvv -u instatestgod__ -pl rockyou.txt"

the output is:
[35mInstagram-Py 2.0.1 ,  Slick Instagram brute force command line tool.
Copyright (C) 2017 The Future Shell , DeathSec.
[0m
[1m[[33m+[0m[1m][0m [35mStarted[0m[33m @ 2018-01-07 14:43:19.000564[0m
[1m[31mfatal error::[0m Tor configuration invalid or server down :: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by antony-jr** [comment]
@ficopang this is not ment for **Windows** , I'm working on a workarround for this but you should most probabily get used to **linux** , You can run this script in **Kali Linux live boot**.
