### ISSUE TITLE
Connection to host failed - Please help me

### ISSUE THREAD

**Issue by noammiz007** [antony-jr/instagram-py#3]
when i start a bruteforce attack so i get an error: fatal error:: Connection to host failed , check your connection and tor configration.

but i set up my configuration correctly like in this video: https://www.youtube.com/watch?v=KZEcFn3Z5L0
please help me.
i install all the stuff in the readme/video
and i know i set up everything correctly but i just get an error.
and i am using a kali linux 2018.1 os

**Comment by antony-jr** [comment]
@noammiz007 Try restarting the **Tor Server**.

**Comment by noammiz007** [comment]
INSTAGRAM-PY CONFIGURATION:
{"api-url": "https://i.instagram.com/api/v1/", "user-agent": "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)", "ig-sig-key": "4f8732eb9ba7d1c8e8897a75d6474d4eb3f5279137431b2aafb71fafe2abe178", "ig-sig-version": "4", "tor": {"server": "127.0.0.1", "port": "9050", "protocol": "socks5", "control": {"password": "", "port": "9051"}}}

**Comment by antony-jr** [comment]
@noammiz007 Could you post the output of this site(http://127.0.0.1:9050) from your web browser while your Tor Server is running.

**Comment by noammiz007** [comment]
This is a SOCKs proxy, not an HTTP proxy.

It appears you have configured your web browser to use this Tor port as an HTTP proxy.

This is not correct: This port is configured as a SOCKS proxy, not an HTTP proxy. If you need an HTTP proxy tunnel, use the HTTPTunnelPort configuration option in place of, or in addition to, SOCKSPort. Please configure your client accordingly.

See https://www.torproject.org/documentation.html for more information.

**Comment by antony-jr** [comment]
thats a good sign... Have you tried restarting your tor server.

**Comment by noammiz007** [comment]
with service tor stop then start?

**Comment by antony-jr** [comment]
yes , You can also do ``` sudo service tor restart ```

**Comment by noammiz007** [comment]
yes,  and when i do service tor status i get this:
● tor.service - Anonymizing overlay network for TCP (multi-instance-master)
   Loaded: loaded (/lib/systemd/system/tor.service; disabled; vendor preset: disabled)
   Active: active (exited) since Thu 2018-03-01 19:41:17 IST; 5s ago
  Process: 7041 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 7041 (code=exited, status=0/SUCCESS)

Mar 01 19:41:17 kali systemd[1]: Stopped Anonymizing overlay network for TCP (multi-instance-master)
Mar 01 19:41:17 kali systemd[1]: Stopping Anonymizing overlay network for TCP (multi-instance-master
Mar 01 19:41:17 kali systemd[1]: Starting Anonymizing overlay network for TCP (multi-instance-master
Mar 01 19:41:17 kali systemd[1]: Started Anonymizing overlay network for TCP (multi-instance-master)
lines 1-10/10 (END)

**Comment by antony-jr** [comment]
Try using the script now

**Comment by noammiz007** [comment]
i get this:
Instagram-Py 2.0.2 ,  Slick Instagram brute force command line tool.
Copyright (C) 2018 The Future Shell , Antony Jr..

[+] Started @ 2018-03-01 19:43:40.675122

and after 2 minutes i still get this:
fatal error:: Connection to host failed , check your connection and tor configuration.

**Comment by antony-jr** [comment]
hmm... That seems strange , Let me try this later and then notify you.. Please stay tuned.

**Comment by noammiz007** [comment]
ok thank you and please dont forget. :)

**Comment by antony-jr** [comment]
@noammiz007 did you see anything like this , ```  [Errno 111] Connection refused ``` along with the error msg ?

**Comment by noammiz007** [comment]
hmm no, only this:
Instagram-Py 2.0.2 ,  Slick Instagram brute force command line tool.
Copyright (C) 2018 The Future Shell , Antony Jr..

[+] Started @ 2018-03-01 19:43:26.895943
fatal error:: Connection to host failed , check your connection and tor configuration.

**Comment by antony-jr** [comment]
@noammiz007 Could please try the new version by upgrading your current installaion using this command.

```
 $ sudo pip install instagram-py --upgrade
```

You don't have to change the configuration , Just restart your tor server before you start your attack.

**Comment by noammiz007** [comment]
ok, now i got a new error:
Instagram-Py 2.0.4 ,  Slick Instagram brute force command line tool.
Copyright (C) 2018 The Future Shell , Antony Jr.

[+] Started @ 2018-03-01 20:32:33.719819
fatal error:: Connection to host failed , check your connection and tor configuration :: SOCKSHTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7f62ee718a58>: Failed to establish a new connection: 0x06: TTL expired',))

**Comment by antony-jr** [comment]
Now I get a clear picture , The next release will fix your issue for sure.

**Comment by antony-jr** [comment]
@noammiz007 I want you to try this too... ( If you have time )
Set your network proxy as your tor server. In firefox , Go to Preferences-> Network Proxy and select manual proxy configuration , enter the SOCKS Host as 127.0.0.1 and port as 9050 then select the socks5 radio button. **Make sure to tick 'Proxy DNS when using SOCKS v5' Checkbox**. Now you are in the deep web. Now Try to go to https://httpbin.org/ip  , If you get any connection error then The issue is with your tor server setup or internet connection ( Like blocking ) , After the test is over make sure to disable proxy.

**Comment by noammiz007** [comment]
and when do you release a new version?

**Comment by antony-jr** [comment]
Could you try the above experiment... :+1:

**Comment by noammiz007** [comment]
ok, trying it now

**Comment by noammiz007** [comment]
this is my settings now as you wanted me to put:
https://i.imgur.com/MpCWwnD.png
but i get this:
https://i.imgur.com/uSOLUn7.png

**Comment by antony-jr** [comment]
Please remove the HTTP Proxy and then , **Tick  'Proxy DNS when using SOCKS v5' Checkbox** ( its super important. Then click okay and try again.

**Comment by noammiz007** [comment]
like this?:

![hm](https://user-images.githubusercontent.com/31467235/36809450-a948fd5c-1cd0-11e8-958d-a761bae75a3a.png)

**Comment by antony-jr** [comment]
Yes ,Click okay and then go to https://httpbin.org/ip

**Comment by noammiz007** [comment]
now any website is not working for me.(loading forever)
including the website you gave me.

**Comment by antony-jr** [comment]
@noammiz007 So then It means that the error is in your tor server setup , Are you sure you did the tor server setup correctly ? Imagine this loading forever in **instagram-py** ( Thats the 2min delay ) and the end result will always be a connection error. ( Max tries exceeded ).

**Comment by noammiz007** [comment]
so how can i fix that?

**Comment by antony-jr** [comment]
That will be brief , I guess you need to google , I've got an important task to finish. I will get a fix as soon as possible. Thank You for reporting your Issue.

**Comment by noammiz007** [comment]
this is the tor folder:
![folder](https://user-images.githubusercontent.com/31467235/36809840-cea3dd96-1cd1-11e8-8f8b-a46923ecc1fc.png)
and this is the tor file(not as a notepad):
[torrc.txt](https://github.com/antony-jr/instagram-py/files/1768612/torrc.txt)

**Comment by noammiz007** [comment]
ok thanks anyway

**Comment by antony-jr** [comment]
Omg , You are missing the torsocks.conf file which is responsible for everything.

**Comment by noammiz007** [comment]
so how can i get it

**Comment by antony-jr** [comment]
@noammiz007 post the output of this command ``` $ sudo service tor status ```

**Comment by noammiz007** [comment]
● tor.service - Anonymizing overlay network for TCP (multi-instance-master)
   Loaded: loaded (/lib/systemd/system/tor.service; disabled; vendor preset: disabled)
   Active: active (exited) since Thu 2018-03-01 21:59:07 IST; 4s ago
  Process: 7674 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
 Main PID: 7674 (code=exited, status=0/SUCCESS)

Mar 01 21:59:07 kali systemd[1]: Starting Anonymizing overlay network for TCP (multi-instance-master
Mar 01 21:59:07 kali systemd[1]: Started Anonymizing overlay network for TCP (multi-instance-master)
lines 1-8/8 (END)

**Comment by antony-jr** [comment]
hmm.. I'm sorry , The file has nothing to do with the error  , just post the output of the above command.

**Comment by antony-jr** [comment]
are you on a live boot ?

**Comment by noammiz007** [comment]
no

**Comment by noammiz007** [comment]
its an installed on a virtual machine

**Comment by antony-jr** [comment]
@noammiz007 there are number of errors using tor in a virtual machine , I recommend you to live boot tails , refer : https://superuser.com/questions/580017/using-tor-on-virtualbox , Bye gotta go now!

**Comment by noammiz007** [comment]
ok thanks

**Comment by noammiz007** [comment]
now i am using a live version and i get this:
fatal error:: tor configuration invalid or server down :: errno 1111 connection refused

**Comment by antony-jr** [comment]
thats a good sign... Did you have tor installed , follow the video tutorial...

**Comment by noammiz007** [comment]
yes i did

**Comment by noammiz007** [comment]
i followed the video

**Comment by noammiz007** [comment]
Os: kali-linux-2018-W08-amd64 - Live
Content: ![content](https://user-images.githubusercontent.com/31467235/36812916-618845a8-1cdb-11e8-939f-5b6d00f9fe1c.png)
torrc: http://pastebin.com/raw/cgVd1MBa
torsocks.conf: http://pastebin.com/raw/RwbHC58X

Service tor status:
![service](https://user-images.githubusercontent.com/31467235/36813043-d1e28a7a-1cdb-11e8-9b86-ef1caf39b0f1.png)

**Comment by antony-jr** [comment]
Where is the configuration file for **instagram-py** ?

**Comment by noammiz007** [comment]
oh 1 sec

**Comment by noammiz007** [comment]
instapy-config.json: http://pastebin.com/raw/PQjHYt57

**Comment by antony-jr** [comment]
Could you do the same experiment we did before , Setting your browser proxy to tor and then loading a website ?

**Comment by noammiz007** [comment]
![same error](https://user-images.githubusercontent.com/31467235/36815312-019fc0aa-1ce3-11e8-943b-519212ab03a4.png)

**Comment by antony-jr** [comment]
It seems like your tor server port or ip must be different...

**Comment by antony-jr** [comment]
Could you post the output of ``` $ nmap 127.0.0.1 ```

**Comment by noammiz007** [comment]
![default](https://user-images.githubusercontent.com/31467235/36815838-a26be4f4-1ce4-11e8-9dd0-0d505ec4a193.png)

**Comment by antony-jr** [comment]
@noammiz007 Did you start the tor server , ``` $ service tor start && service tor status ```

**Comment by noammiz007** [comment]
yes

**Comment by noammiz007** [comment]
![default](https://user-images.githubusercontent.com/31467235/36815961-1ae2e6d0-1ce5-11e8-9dcc-c4f3f41a7836.png)

**Comment by antony-jr** [comment]
but it seems that tor never openned any port on our loopback ?? Try restarting the tor server and then wait a bit and then do the nmap. If all fails , Download the tor browser and open it , It will show why we can't get connected to tor ( Could be your ISP ). If there is connectivity in the tor browser then set the tor port and control port in the instagram-py configuration from the settings show in the network proxy of the tor browser this will work as long as the tor browser is openned ( We simply use the inbuilt tor server )

**Comment by antony-jr** [comment]
@noammiz007 Any progress ?

**Comment by noammiz007** [comment]
i downloaded tor browser and the browser is working

**Comment by antony-jr** [comment]
Perfect , Now do this.... 

>  If there is connectivity in the tor browser then set the tor port and control port (Most probabily tor port + 1 , Ex: Tor Port = 9050 then Control Port = 9051) in the instagram-py configuration from the settings show in the network proxy of the tor browser this will work as long as the tor browser is openned ( We simply use the inbuilt tor server )

**Comment by noammiz007** [comment]
but i had to use another user cuz i always used a root account so now i installed in on another account.

**Comment by noammiz007** [comment]
ok its starting to confuse me, can you please connect to my virtual machine or there is any way you can do this for me please? cuz now its saying another thin about tor is not the (something-i forgot) file. the incident is reported

**Comment by noammiz007** [comment]
or can i atleast screenshare it for you? please

**Comment by noammiz007** [comment]
oh nvm, but now i get the fatal error tor configuration invalid again

**Comment by noammiz007** [comment]
![default](https://user-images.githubusercontent.com/31467235/36817584-4ca4f17c-1cea-11e8-8d87-e6bde7aca063.png)

**Comment by noammiz007** [comment]
dude, do you have a discord so i can screenshare for you instantly?

**Comment by noammiz007** [comment]
are you online now?

**Comment by antony-jr** [comment]
I'm busy right now , I will try to find the cause for all these errors.. ( But It does work great in my linux os )

**Comment by antony-jr** [comment]
@noammiz007 The only problem now is that your Tor server never starts... Verify if your tor server has openned a port with this command ``` $ nmap 127.0.0.1 ``` ( This is the loop back address ).

If tor is working good , The output should be something like this... 

```
[antonyjr@Liz ~]$ nmap 127.0.0.1

Starting Nmap 7.60 ( https://nmap.org ) at 2018-03-01 23:30 IST
Nmap scan report for localhost.localdomain (127.0.0.1)
Host is up (0.000070s latency).
Not shown: 998 closed ports
PORT     STATE SERVICE
9050/tcp open  tor-socks

Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds
[antonyjr@Liz ~]$ 
```

The port 9050 with state open for the service **tor-socks** , If you have this output then instagram-py will start working with no errors.

**Comment by noammiz007** [comment]
omg its fixed.
![default](https://user-images.githubusercontent.com/31467235/36863089-659139e6-1d91-11e8-92dc-4accc45b6fac.png)
thank you very much for the help!
and i am using the installed version.

**Comment by antony-jr** [comment]
@noammiz007 That sounds good :heart:  , Care to share what you did to fix this issue , It can help others to fix this issue , if they stumble upon something like yours... :+1: 

Thank your for reporting the issue.. Use instagram-py with these args to see how the magic works! ``` $ instagram-py -vvv -c -u noammiz007 -pl small.txt ```.

**PLEASE SEE THAT WITHOUT THE '-c' POSITIONAL ARGUMENT , INSTAGRAM-PY WILL NOT RESUME THE ATTACK**

See ya! :smile:  Close this issue if its solved and Thank you for trying out my tool! 

If you want to learn more , see about **Instagram-Py Scripting** in the README of this repo , it helps you to **send messages to your phone when a account is cracked , multiple attack vectors and much more customization** ( Python scripting supported ) ( you must know python to do the customization though )

**Comment by noammiz007** [comment]
i think the problem was really with the tor. i am not really sure how i fixed it. i think the problem has occured because i didnt have the torsocks file. and btw i really like your tool.
