### ISSUE TITLE
Permission denied: 'var/run/tor/control/authcookie'

### ISSUE THREAD

**Issue by Modifero** [antony-jr/instagram-py#4]
Hello Mr Jr!

i've tried to delete the # before ControlPort
then when i trying to continue:

fatal error:: Tor configuration invalid or server down :: Authentication failed: unable to read '/var/run/tor/control.authcookie' ([Errno 13] Permission denied: '/var/run/tor/control.authcookie')

would you mind to help?

**Comment by noammiz007** [comment]
screenshot please?

**Comment by antony-jr** [comment]
Hey @Modifero ,

Try with **sudo**

**Comment by antony-jr** [comment]
Hey @Modifero , Just verified , adding **sudo** to the command fixed this issue. Reopen this if you run into this issue again! **Thank you for your Time**.
