### ISSUE TITLE
Tor Configuration invalid or server down

### ISSUE THREAD

**Issue by andika04kd** [antony-jr/instagram-py#5]
How to solve?[](https://www.imageupload.co.uk/image/E9j7)

**Comment by noammiz007** [comment]
please give more information? for example: a screenshot, full output.

**Comment by andika04kd** [comment]
https://www.imageupload.co.uk/image/E9j7

**Comment by noammiz007** [comment]
did you installed tor?

**Comment by andika04kd** [comment]
Yes already

**Comment by noammiz007** [comment]
and did u enabled it with service tor start?

**Comment by andika04kd** [comment]
How? Sorry im just new for it

**Comment by noammiz007** [comment]
write: service tor start

**Comment by andika04kd** [comment]
Unknown command tor? 
https://www.imageupload.co.uk/image/E9jy

**Comment by noammiz007** [comment]
ye i get this too, hold on. i need to get the command for service

**Comment by noammiz007** [comment]
@antony-jr how do i run tor service on termux?

**Comment by noammiz007** [comment]
@antony-jr and when do the install stuff are being saved at in the phone?

**Comment by antony-jr** [comment]
@noammiz007 If want to run tor service in termux , it needs a lot of work... But it is possible

**Comment by noammiz007** [comment]
@antony-jr 
wdu mean? like what do i need to do? i googled it but i couldnt find anything

**Comment by antony-jr** [comment]
Installation is simple but running it as a service is hard!

**Comment by antony-jr** [comment]
# To Install Tor
``` $ apt install tor ```

**Comment by noammiz007** [comment]
@antony-jr any tutorial?
i already installed tor

**Comment by antony-jr** [comment]
I think it will take time , look at this issue https://github.com/termux/termux-packages/issues/1965

**Comment by noammiz007** [comment]
@antony-jr its ok i have all the time in the world

**Comment by noammiz007** [comment]
@antony-jr do i need to download https://www.haproxy.org/ ?

**Comment by antony-jr** [comment]
no its just an example...

**Comment by noammiz007** [comment]
@antony-jr i still dont understand what i need to download

**Comment by antony-jr** [comment]
It simply implies that we can't do tor in android for now! Therefore we are limited with linux,windows and macosx

**Comment by noammiz007** [comment]
@antony-jr ah.

**Comment by andika04kd** [comment]
Damn,  so this script not working?

**Comment by noammiz007** [comment]
Not with termux but on pc

**Comment by antony-jr** [comment]
@andika04kd The script works on termux but **tor** does not work with termux ( not as a service ). So the issue is with **termux** and not **instagram-py**.

**Comment by antony-jr** [comment]
@andika04kd Closing this issue as this concerns with an issue in **termux** , Reopen if anything goes wrong in a pc , Please wait for the next major release which will have all the feature requested ( Also support for termux ) , **Thank You for your time.**
